### ISSUE TITLE
Is Cherokee....kinda sorta.....abandoned?

### ISSUE THREAD

**Issue by n0nag0n** [cherokee/webserver#1210]
I've used Cherokee a little bit for testing, but I hesitate to use it for production because development seems to have slowed down significantly and if something big security wise came up.....would it be addressed quickly?

So....don't hate me for bringing it up, cause I love what I've seen of Cherokee, but is Cherokee officially in maintenance mode until further notice? Is there a road map of sorts for any new features?

**Comment by skinkie** [comment]
> would it be addressed quickly?

Since many of my personal and professional services are running on cherokee even using specialised handlers, as indicated in the past this will be addressed quickly. The problem is the actually reproducability of the remaining known issues. The last fix (April 12) must have been in Cherokee since the start, but nobody was actually able to trigger it consistently (and it was not brought up in Coverity). When there was a service that consistently broke Cherokee repeatedly it was easy te fix.

I am aware of another type of bug which is also very difficult to trigger, but seem to consistenly stop the serving of any request. For weeks a server is running with hellgrind, so QA/development effort is put into the project, but I'll not publish a public roadmap, considering the number of people working on Cherokee is limited.

**Comment by n0nag0n** [comment]
Well that's good to know. :) I hate configuring and working with apache with a passion. I have wasted so much time fighting apache configs to get it to do what I want it to do and I've been in this unstable relationship with apache for 7+ years as a full stack dev. Cherokee was a breath of fresh air so I could actually get to work coding and not have to worry about touching server configs :-/ Every time I have to hop in there I feel like the YUNO guy...

**Comment by skinkie** [comment]
For me #1179 would be something that would be very useful for many people. But then again, anyone with a bit of patience should be able to set up acmetool, and a fixed path to the certificates. I would like to prevent to create yet another implementation. So yes there are goals, but help would be definitely required on all subjects to move forward beyond a stable system with a pretty configuration site.

**Comment by n0nag0n** [comment]
Yeah, no I agree, some help would be great. If I could just learn C now.....

**Comment by skinkie** [comment]
Closing the issue :) since I am actually commiting code again ;)
