### ISSUE TITLE
Question: is this stil going?

### ISSUE THREAD

**Issue by marcdraco** [cherokee/webserver#1219]
Updates are infrequent, milestones missed and the list of users has vanished from GitHub. This looks like a stonking good Webserver and I was itching to use it (I found it in the Apline repo) but it seems to be slow slipping away. I wish I could help but it looks like I'm going to have to return to nGinX or Lightthpd which is a shame because that Python front end looks like a real time saver, particularly for people who don't have time to sit at a computer all day!

I'm rooting for you and hope you can find some more contributors to lighten the load! (No pun intended.)

**Comment by skinkie** [comment]
The point is that you don't ask a question and only mention the obvious: people move on. As mentioned in other issues, if there is a bug, this bug gets fixed as soon as possible. Like always has been done. This _question_ is also answered within an hour outside business hours, on a Saturday. If you want to contribute to this project, you have seen the wish list, which includes things like documentation that an ordinary interested personal that masters the English language could write. But stating you have to return to something else because you actually can't find a problem, is pretty _bizarre_.

**Comment by marcdraco** [comment]
I can see plenty of problems - mainly that the project appears to be moribund - and when I see 404s like this (http://cherokee-project.com/cherokee-domain-list.html) my confidence is shattered. Your brusque remark settles it for me, with that kind of attitude people won't want to help. I have better things to do with my time.

**Comment by skinkie** [comment]
Reviewing the number of contributions on github, I see you do.
