### ISSUE TITLE
Repetition of reg expressions in redirects

### ISSUE THREAD

**Issue by finnianr** [cherokee/webserver#1268]
I am looking at the official documentation for redirection. In  [this particular example](https://cherokee-project.com/doc/media/images/cookbook_drupal_dir_rules_1.png)  is shows that you first create a reg expression rule, then assign an internal redirect handler for that rule. But in the handler the exact same regular expression is specified again. This is counter to the DRY principle. Why the need for this repetition?

**Comment by skinkie** [comment]
@finnianr this is because the _match_ is how you arrive at the _handler_, and the _handler_ that does the operation are not integrated. The matches only purpose is to get you there, but may also be more generic, you could a directory match with a redirection for example. In addition the handler may have more replacements making it not a 1:1 relationship.
