### ISSUE TITLE
SSL not working with sub-subdomains longer than SSL_MAX_SSL_SESSION_ID_LENGTH

### ISSUE THREAD

**Issue by jgdye** [cherokee/webserver#975]
Using both the compiled stable nightly and the Ubuntu PPA version on server x64, as well as compiled stable nightly on Raspbian, when I try to add SSL to a sub-subdomain (e.g. x.y.z.com), I get the following error:

[04/06/2013 15:43:38.021](error) cryptor_libssl.c:506 - Unable to set SSL
session-id context for 'x.y.z.com':
error:140DB111:SSL routines:SSL_CTX_set_session_id_context:ssl session id
context too long | The issue seems to be related to your system. 

When I remove one of the levels of sub-domain, it works as expected.  I've chained the certificate files, and the same certificate file works on Apache, postfix, and dovecot.  I also chained a certificate for y.z.com using the same method, and cherokee worked without error.

**Comment by arideden** [comment]
I'm posting here because this thread has a lot of google-juice.
I'm still getting this error with Cherokee 1.2.103. It turned out to be the length of the nick used to identify the vserver I was configuring with SSL. Through trial and error I have determined a 32 character maximum nick length to configure SSL on a vserver.
The solution (if you your overly domain choice is made for you) is to use some small string for the vserver's nick, and change the vserver's host match from nick, to regsub. Enter in your domain, preceding special characters (e.g. .) by \.

**Comment by skinkie** [comment]
Could you at least confirm that the github version works for you?

**Comment by arideden** [comment]
Apologies skinkie, I recognise this is a developer forum, but the comment was intended for dumb sysadmins googling for the error message. The server I'm working on is a production CentOS 6 server with the Cherokee package installed from EPEL. I didn't consider testing a dev version on a production system.
(Although now that I've spent some time to compare the release date of 1.2.103 with the date this thread was started, I realise the problem is likely fixed in the current github version).
